---
# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/GKECluster/v1beta1@v0.16.0

apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: gke-crossplane-cluster
spec:
  forProvider:
    #initialClusterVersion: "1.19"
    ipAllocationPolicy:
      useIpAliases: true
    defaultMaxPodsConstraint:
      maxPodsPerNode: 110
    addonsConfig:
      cloudRunConfig:
        disabled: true
      dnsCacheConfig:
        enabled: false
      gcePersistentDiskCsiDriverConfig:
        enabled: true
      horizontalPodAutoscaling:
        disabled: true
      httpLoadBalancing:
        disabled: false
      istioConfig:
        disabled: true
        auth: "AUTH_NONE"
      kalmConfig:
        enabled: false
      kubernetesDashboard:
        disabled: true
      networkPolicyConfig:
        disabled: false
    location: us-central1-b
    binaryAuthorization: 
      enabled: false
    legacyAbac:
      enabled: false
    loggingService: "none"
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    monitoringService: "none"
---

# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/NodePool/v1alpha1@v0.16.0

apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: gke-crossplane-np
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 2
      minNodeCount: 0  
    clusterRef:
      name: gke-crossplane-cluster
    config:
      diskSizeGb: 100
      imageType: cos_containerd
      labels:
        test-label: crossplane-created
      machineType: n1-standard-4
    initialNodeCount: 0
    locations:
      - us-central1-b
    management:
      autoRepair: true
      autoUpgrade: true

---

# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/NodePool/v1alpha1@v0.16.0

apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: test-np-reconciliation
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 2
      minNodeCount: 0  
    clusterRef:
      name: gke-crossplane-cluster
    config:
      diskSizeGb: 100
      imageType: cos_containerd
      labels:
        test-label: crossplane-created
      machineType: e2-standard-2
    initialNodeCount: 1
    locations:
      - us-central1-b
    management:
      autoRepair: true
      autoUpgrade: true